[package]
name = "minicraft-rs"
version = "0.1.0"
authors = ["bananu7"]
edition = "2018"

[dependencies]
glium = "*"
glm = "*"
num = "*"
roxmltree = "*"
image = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
gltf = "0.15"